version: '3.8'

# Services are the containers we want to run
services:
  # 1. The Database Service
  db:
    image: postgres:latest
    container_name: my-postgres-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=mysecretpassword

  # 2. The Application Service
  app:
    build: . # This tells Compose: "Build the Dockerfile in this directory"
    container_name: todo-api-container
    ports:
      - "8080:8080"
    depends_on:
      - db # CRITICAL. Will not start app until the db service is healthy
    environment:
      # Docker Compose gives us this private, internal 'db' hostname.
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=mysecretpassword

# Defines the "external hard drive"
volumes:
  postgres_data: {}